@startuml

使用者 -> 前端: 上傳Excel空白表單
前端 -> 後端: 儲存Excel空白表單

使用者 -> 前端: 上傳Excel欄位綁定表
前端 -> 前端: 驗證資料及格式
前端 -> 後端: 綁定格及欄位資料
前端 -> 後端: 儲存Excel綁定表

後端 --> 前端: 返回空白表單
後端 --> 前端: 同步iSLM表格
後端 --> 前端: Excel綁定表/JSON物件

loop 使用iSLM
  alt iSLM表格編輯
    使用者 -> 前端: 編輯iSLM表格
    前端 -> 前端: 資料驗證
    前端 -> 後端: 欄位資料
  else Excel表單編輯
    loop
      使用者 -> 前端: 編輯表單
      後端 --> 前端: 返回Excel綁定表/JSON物件
      前端 -> 前端: 驗證及更新綁定值
      前端 -> 前端: 同步iSLM表格
      前端 -> 後端: iSLM欄位值更新
      前端 -> 後端: 儲存Excel表單
    end
  else 更新Excel綁定表
    loop
      使用者 -> 前端: 編輯/上傳Excel綁定資料
      前端 -> 前端: 驗證資料及格式
      前端 -> 後端: 儲存Excel綁定表/JSON物件
    end
  end
end
@enduml